let expert = Expert()
let character = Character()
character.moveForward()
character.collectGem()
character.moveForward()
character.turnRight()
expert.moveForward()
expert.turnLockUp()
character.moveForward()
character.moveForward()
expert.turnLockDown()
expert.turnLockDown()
character.moveForward()
character.collectGem()
